const express = require('express');
const { verifyToken } = require('../middleware/jwt');
const { createEvent, getEvents, getEventById, applyToEvent, submitWork, selectWinner, timeoutDistribute, getEventParticipants, getEventSubmissions } = require('../controllers/eventController');
const router = express.Router();
router.post('/', verifyToken, createEvent);
router.get('/', getEvents);
router.get('/:id', getEventById);
router.get('/:id/participants', getEventParticipants);
router.get('/:id/submissions', getEventSubmissions);
router.post('/:id/apply', verifyToken, applyToEvent);
router.post('/:id/submit', verifyToken, submitWork);
router.post('/:id/winners', verifyToken, selectWinner);
router.post('/:id/timeout', verifyToken, timeoutDistribute);
module.exports = router;
